services:
  preprocessing:
    build:
      context: .
      dockerfile: services/preprocessing/Dockerfile
    user: "${LOCAL_UID:-1000}:${LOCAL_GID:-1000}"
    image: celesify-preprocessing:latest
    environment:
      - KAGGLE_USERNAME
      - KAGGLE_KEY
    volumes:
      - ./data:/workspace/data
      - shared_outputs:/workspace/outputs
    working_dir: /workspace

  training:
    build:
      context: .
      dockerfile: services/training/Dockerfile
    user: "${LOCAL_UID:-1000}:${LOCAL_GID:-1000}"
    image: celesify-training:latest
    volumes:
      - shared_outputs:/workspace/outputs
    working_dir: /workspace

  streamlit:
    build:
      context: .
      dockerfile: services/streamlit/Dockerfile
    user: "${LOCAL_UID:-1000}:${LOCAL_GID:-1000}"
    image: celesify-streamlit:latest
    volumes:
      - shared_outputs:/workspace/outputs
    working_dir: /workspace
    ports:
      - "8501:8501"
    depends_on:
      - training

volumes:
  shared_outputs:
