"""
Model export and artifact persistence.

This module handles:
- Saving metrics to JSON
- Saving models to joblib format
- Converting to ONNX format with error handling
- Logging and status tracking
"""

from __future__ import annotations

import os
import traceback
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, cast

import joblib
import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from skl2onnx import convert_sklearn
from skl2onnx.common.data_types import FloatTensorType

from celesify.core.json_utils import as_jsonable, write_json
from celesify.core.logging import log

SERVICE = "training"


def save_metrics_json(output_dir: Path, filename: str, metrics: dict[str, Any]) -> None:
    """
    Save metrics dictionary to JSON file.

    Args:
        output_dir: Directory to write to.
        filename: Output filename (with .json extension).
        metrics: Dictionary to serialize.
    """
    output_dir.mkdir(parents=True, exist_ok=True)
    write_json(output_dir / filename, as_jsonable(metrics))
    log(SERVICE, f"Wrote {filename}")


def save_model_joblib(output_dir: Path, filename: str, model: RandomForestClassifier) -> None:
    """
    Save model to joblib format.

    Args:
        output_dir: Directory to write to.
        filename: Output filename (typically "model.joblib").
        model: Trained RandomForestClassifier instance.
    """
    output_dir.mkdir(parents=True, exist_ok=True)
    model_path = output_dir / filename
    joblib.dump(model, model_path)
    log(SERVICE, f"Wrote {filename}")


def export_onnx_model(
    output_dir: Path,
    model: RandomForestClassifier,
    x_sample: pd.DataFrame,
) -> bool:
    """
    Convert trained model to ONNX format.

    Handles conversion errors gracefully, writing error details to a log file
    and status JSON for debugging.

    Args:
        output_dir: Directory to write model and status files.
        model: Trained RandomForestClassifier.
        x_sample: Sample input (used to infer input shape).

    Returns:
        True if export succeeded, False otherwise.
    """
    output_dir.mkdir(parents=True, exist_ok=True)

    model_path = output_dir / "model.onnx"
    status_path = output_dir / "onnx_export_status.json"
    error_log_path = output_dir / "onnx_export_error.log"

    try:
        log(SERVICE, "Converting model to ONNX format...")

        # Convert to ONNX
        x_sample_float32 = x_sample.astype(np.float32)
        onnx_result = convert_sklearn(
            model,
            initial_types=[("input", FloatTensorType([None, x_sample_float32.shape[1]]))],
        )

        # Handle both tuple and direct return formats
        onnx_model = onnx_result[0] if isinstance(onnx_result, tuple) else onnx_result

        # Write model bytes
        model_path.write_bytes(onnx_model.SerializeToString())

        # Clean up any prior error log
        if error_log_path.exists():
            error_log_path.unlink()

        # Write success status
        write_json(
            status_path,
            {
                "status": "completed",
                "timestamp_utc": datetime.now(timezone.utc).isoformat(),
                "model_path": str(model_path),
                "source_model_type": f"{model.__class__.__module__}.{model.__class__.__name__}",
                "onnx_export_model_type": f"{model.__class__.__module__}.{model.__class__.__name__}",
            },
        )

        log(SERVICE, "Wrote model.onnx")
        return True

    except Exception as exc:
        # Extract first line of error for logging
        error_summary = str(exc).splitlines()[0][:500]

        # Write full traceback
        error_log_path.write_text(traceback.format_exc(), encoding="utf-8")

        # Write error status
        write_json(
            status_path,
            {
                "status": "failed",
                "timestamp_utc": datetime.now(timezone.utc).isoformat(),
                "error_type": type(exc).__name__,
                "error_message": error_summary,
                "error_log": str(error_log_path),
            },
        )

        log(SERVICE, f"ONNX export failed ({type(exc).__name__}); details in {error_log_path}")
        return False


def write_skip_placeholder(
    output_dir: Path,
    required_files: list[str],
) -> None:
    """
    Write placeholder artifacts when input data is not available.

    Used during initial setup or validation when processed data hasn't
    been generated by the preprocessing stage yet.

    Args:
        output_dir: Directory to write placeholder files.
        required_files: List of files that are missing.
    """
    output_dir.mkdir(parents=True, exist_ok=True)

    placeholder = {
        "status": "skipped_no_processed_data",
        "required_files": required_files,
        "timestamp_utc": datetime.now(timezone.utc).isoformat(),
    }

    write_json(output_dir / "baseline_metrics.json", placeholder)
    write_json(output_dir / "tuned_metrics.json", placeholder)
    write_json(output_dir / "best_params.json", {"status": "not_run"})
    write_json(output_dir / "feature_importance.json", {"status": "not_run"})

    log(SERVICE, "Wrote placeholder artifacts (no processed data available)")
